# Generated by Django 5.1.7 on 2026-07-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_classes', '0001_initial'),
        ('taxon_profiles', '0014_alter_taxonprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonprofilesnavigationentry',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AddField(
            model_name='taxonprofile',
            name='object_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_classes.objectclass'),
        ),
    ]
