# Generated by Django 5.1.7 on 2026-07-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_classes', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('taxon_profiles', '0015_alter_taxonprofilesnavigationentry_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxonprofile',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='taxonprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('morphotype__isnull', False), ('object_class__isnull', False)), fields=('taxon_profiles', 'taxon_source', 'name_uuid', 'morphotype', 'object_class'), name='tp_unique_taxon_morphotype_objectclass'),
        ),
        migrations.AddConstraint(
            model_name='taxonprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('morphotype__isnull', False), ('object_class__isnull', True)), fields=('taxon_profiles', 'taxon_source', 'name_uuid', 'morphotype'), name='tp_unique_taxon_morphotype_no_objectclass'),
        ),
        migrations.AddConstraint(
            model_name='taxonprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('morphotype__isnull', True), ('object_class__isnull', False)), fields=('taxon_profiles', 'taxon_source', 'name_uuid', 'object_class'), name='tp_unique_taxon_objectclass_no_morphotype'),
        ),
        migrations.AddConstraint(
            model_name='taxonprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('morphotype__isnull', True), ('object_class__isnull', True)), fields=('taxon_profiles', 'taxon_source', 'name_uuid'), name='tp_unique_taxon_no_morphotype_no_objectclass'),
        ),
    ]
