# Generated by Django 6.1 on 2026-09-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon_profiles', '0016_alter_taxonprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonprofile',
            name='featured_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taxonprofile',
            name='featured_until',
            field=models.DateField(null=True),
        ),
    ]
