# Generated by Django 5.1.7 on 2026-07-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature_guides', '0011_delete_natureguidestaxonnamesview_and_more'),
        ('object_classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metanode',
            name='object_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_classes.objectclass'),
        ),
        migrations.AlterField(
            model_name='matrixfilter',
            name='filter_type',
            field=models.CharField(choices=[('ColorFilter', 'Color'), ('RangeFilter', 'Range of numbers'), ('NumberFilter', 'Numbers'), ('DescriptiveTextAndImagesFilter', 'Text and images'), ('TaxonFilter', 'Taxonomic filter'), ('TextOnlyFilter', 'Text only')], max_length=50),
        ),
    ]
