# Generated by Django 5.1.7 on 2026-03-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_auto_20201207_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryEntryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.glossary')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('glossary', 'name')},
            },
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.glossaryentrycategory'),
        ),
    ]
