# Generated by Django 5.1.7 on 2026-07-21 05:54

import app_kit.generic
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('primary_language', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255, null=True)),
                ('published_version', models.IntegerField(null=True)),
                ('current_version', models.IntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('messages', models.JSONField(null=True)),
                ('global_options', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Object classes',
                'verbose_name_plural': 'Object classes',
            },
            bases=(app_kit.generic.GenericContentMethodsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ObjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='object_classes.objectclasses')),
            ],
            options={
                'verbose_name': 'Object class entry',
                'verbose_name_plural': 'Object class entries',
                'ordering': ['name'],
                'unique_together': {('object_classes', 'scientific_name')},
            },
        ),
        migrations.CreateModel(
            name='ObjectClassTaxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_latname', models.CharField(max_length=255)),
                ('taxon_author', models.CharField(max_length=255, null=True)),
                ('taxon_source', models.CharField(max_length=255)),
                ('taxon_include_descendants', models.BooleanField(default=False)),
                ('taxon_nuid', models.CharField(max_length=255)),
                ('name_uuid', models.UUIDField()),
                ('object_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxon_mappings', to='object_classes.objectclass')),
            ],
            options={
                'verbose_name': 'Object class taxon mapping',
                'verbose_name_plural': 'Object class taxon mappings',
                'ordering': ['taxon_latname'],
                'unique_together': {('object_class', 'name_uuid')},
            },
        ),
    ]
