# Generated by Django 6.1 on 2026-09-23 12:17

import app_kit.features.frontend.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_frontend_frontend_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendResourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('resource_file', models.FileField(upload_to=app_kit.features.frontend.models.frontend_resource_file_upload_to)),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.frontend')),
            ],
            options={
                'unique_together': {('frontend', 'identifier')},
            },
        ),
    ]
