# Generated by Django 3.1 on 2021-01-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nature_guides', '0002_auto_20201013_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixFilterRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_space', models.JSONField(null=True)),
                ('restriction_type', models.CharField(choices=[('selected', 'is selected')], max_length=50)),
                ('matrix_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nature_guides.matrixfilter')),
                ('matrix_filter_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nature_guides.matrixfilterspace')),
            ],
            options={
                'unique_together': {('matrix_filter', 'matrix_filter_space')},
            },
        ),
    ]
