# Generated by Django 3.1 on 2020-11-19 12:35

import app_kit.features.fact_sheets.models
import app_kit.generic
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=355)),
                ('title', models.CharField(max_length=355, null=True)),
                ('navigation_link_name', models.CharField(max_length=355, null=True)),
                ('content', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Fact sheet',
                'verbose_name_plural': 'Fact sheets',
            },
        ),
        migrations.CreateModel(
            name='FactSheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('primary_language', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255, null=True)),
                ('published_version', models.IntegerField(null=True)),
                ('current_version', models.IntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('messages', models.JSONField(null=True)),
                ('global_options', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': 'Fact sheets',
                'verbose_name_plural': 'Fact sheets',
            },
            bases=(app_kit.generic.GenericContentMethodsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FactSheetTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.FileField(upload_to=app_kit.features.fact_sheets.models.factsheet_templates_upload_path)),
                ('fact_sheets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_sheets.factsheets')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactSheetTaxa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_latname', models.CharField(max_length=255)),
                ('taxon_author', models.CharField(max_length=255, null=True)),
                ('taxon_source', models.CharField(max_length=255)),
                ('taxon_include_descendants', models.BooleanField(default=False)),
                ('taxon_nuid', models.CharField(max_length=255)),
                ('name_uuid', models.UUIDField()),
                ('fact_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_sheets.factsheet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactSheetImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=355, null=True)),
                ('image', models.ImageField(upload_to=app_kit.features.fact_sheets.models.factsheet_images_upload_path)),
                ('fact_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_sheets.factsheet')),
            ],
        ),
        migrations.AddField(
            model_name='factsheet',
            name='fact_sheets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_sheets.factsheets'),
        ),
    ]
