# Generated by Django 3.1 on 2021-02-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsheetimages',
            name='requires_translation',
            field=models.BooleanField(default=False),
        ),
    ]
