# Generated by Django 3.1.14 on 2022-06-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_sheets', '0002_factsheetimages_requires_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactSheetImages',
        ),
    ]
