# Generated by Django 3.1 on 2020-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_sheets', '0003_auto_20201120_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsheet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
