# Generated by Django 3.1 on 2020-12-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_sheets', '0004_factsheet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factsheetimages',
            old_name='content',
            new_name='microcontent_type',
        ),
    ]
