# Generated by Django 3.1 on 2020-12-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_sheets', '0005_auto_20201207_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsheetimages',
            name='text',
            field=models.CharField(max_length=355, null=True),
        ),
    ]
